services:
  ion-sfu:
    image: pionwebrtc/ion-sfu:latest
    container_name: rtcemu-ion-sfu
    ports:
      - "7000:7000"
      - "5000-5200:5000-5200/udp"
    restart: unless-stopped

  demo-ui:
    image: nginx:1.27-alpine
    container_name: rtcemu-demo-ui
    depends_on:
      - ion-sfu
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    restart: unless-stopped
